export enum EasingFunction {
    linear = 'linear',
    easeInQuad = 'easeInQuad',
    easeOutQuad = 'easeOutQuad',
    easeInOutQuad = 'easeInOutQuad',
    easeInCubic = 'easeInCubic',
    easeOutCubic = 'easeOutCubic',
    easeInOutCubic = 'easeInOutCubic',
    easeInQuart = 'easeInQuart',
    easeOutQuart = 'easeOutQuart',
    easeInOutQuart = 'easeInOutQuart',
    easeInQuint = 'easeInQuint',
    easeOutQuint = 'easeOutQuint',
    easeInOutQuint = 'easeInOutQuint',
    easeOutExpo = 'easeOutExpo',
}